### ISSUE TITLE
Logging stack using Loki

### ISSUE THREAD

**Issue by Kristian-ZH** [gardener/logging#72]
# Current tasks
  - [x] logging documentations [this](https://github.com/gardener/logging/pull/58) and [this](https://github.com/gardener/gardener/pull/2601). 
  - [x] [gardenctl](https://github.com/gardener/gardenctl/pull/213) related changes.
  - [x] Add `fluent-bit` filters and parsers for all of the extensions.
  - [x] Make fluent-bit aware of `testing` and `hibernated` clusters (Currently if there is a log messages just before the hibernation or messages from `tf-pods` the `fluent-bit` tries to flush them into non existing Loki, because it is already deleted ).
  - [x] Remove the admission that is annotating pods with `fluentbit.io/exclude` [bug]
  - [x] Upgrade loki to 1.6.0
  - [x] Deploy logging stack as early as possible in shoot reconciliation flow: https://github.com/gardener/gardener/issues/2457
  - [x] Fix parser:lbReadvertiserParser time format [PR](https://github.com/gardener/gardener-extension-provider-aws/pull/178)
  - [x] Use Fluent-bit tags to extract k8s metadata when it can not be obtained from the Api-server ( This change will prevent sending shoot logs to `garden` namespace)
  - [x] Investigate Fluent-bit `entry out of order` issue
      - [x] Container restart scenario: Add ContainerID in stream identity in Fluent-bit plugin
      - [x] fluent-bit logs are flushed async -> try to increase the flush interval
      - [x] implement ID per stream
  - [x] Expose Logging configurations
  - [x]  Deliver Fluent-bit plug-in lib only https://github.com/gardener/logging/issues/62
  - [x] PoC/Research bulk send logs to Loki - contribute to Fluent-bit plug-in
  - [x] Rework Logging dashboards: [gardener/gardener#2945](https://github.com/gardener/gardener/pull/2945)
  - [x] Review the labels and remove the unnecessary ones 
  - [x] Integration test which simulates logging stack in a loaded seed
     - [ ] Tail plugin silently loses logs under high load [fluent-bit #2723](https://github.com/fluent/fluent-bit/issues/2723)
     - [x] Mitigate in the Integration test with 1 minute waiting time.
  - [x] Deploy custom plugin as init container
  - [x] Implement Loki tenants (Security)
  - [x] Add `priorityClassName` to fluent-bit pods
  - [x] Metrics for the custom plugin
     - [x] Research how to expose custom metrics
     - [x] Create custom metrics and Grafana Dashboard: https://github.com/gardener/gardener/pull/3188
     - [x] Prometheus alerts
  - [x] Expose Cloud-Controller-Manager and CSI-Driver to the end-users via Dashboards
  - [x] Separate the seed and shoot logging stack deletion to avoid unwanted cluster scope resource deletion.
  - [x] Investigate slow volume attachment for Loki.
  - [x] Make Loki inode and volume-based curator.
  - [x] Make VPA logs available for end-users.
  - [ ] Make integration test to check for `entry out of order` issue
  - [ ] Make integration test stable

# Future improvements
  - [ ] Fetch logs from deleting shoot and store them to the central Loki instance
  - [ ] Fetch logs from the shoot nodes
  - [ ] Upgrade to Loki 2.0
  - [ ] Fetch Kernel logs: https://github.com/gardener/gardener/issues/2991 - TBD
  - [ ] Throttling filter in fluent-bit plugin - cut logs from pods which are flooding aggressively - TBD
     - [ ] Create throttling filter
     - [ ] Create metrics based on which pod logs are throttled
     - [ ] Create alert when logs are throttled

**Comment by Kristian-ZH** [comment]
Since the issues are moved into gardener/gardener, we do not need to track the backlog here.

/close
